spring:
  data:
    solr:
      host: http://192.168.109.132:8088/solr
  datasource:
    #数据库地址
    url: jdbc:mysql://localhost:3306/jj-v9?serverTimezone=UTC
    #用户名
    username: root
    #密码
    password: cKnBBJhZMfy7pZ8x6Y1mTYM5jMKzXsKT1Flo2Tm1PtyMR/jTeJLgxq9jDNsNUg/bS+Ao4FD/MxA/KXHS2iqTpQ==
    #驱动类
    driver-class-name: com.mysql.jdbc.Driver
    #连接源，springboot默认是HikariCP，现改为alibaba的druid
    druid:
      #初始化时建立物理连接数
      initial-size: 10
      #最大连接数
      max-active: 100
      # 最小连接池数量
      min-idle: 10
      #是否支持
      filter:
        config:
          enabled: true
      connection-properties: config.decrypt=true;config.decrypt.key=${public-key}

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMzamcK9OxJjrAoyHhxffFBsEXsrOFKuqwuInEOZMGZSnwNqkUZ9VVsktdmDfe2y4oJgvcZDWtGdG2bBymBaIgUCAwEAAQ==

dubbo:
  application:
    name: search-service
  registry:
    protocol: zookeeper
    address: 192.168.109.132:2181
  protocol:
    port: 28802




